apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-redis-auth
  labels:
    {{- include "myflask.labels" . | nindent 4 }}
data:
  rdshost: {{ .Values.redis_host }}
  rdspasswd: {{ .Values.redis_passwd }}